### PR TITLE
Add atlassian lifecycle endpoints

### LINKED ISSUE #30: Add Atlassian lifecycle endpoints
Atlassian communicates via webhooks, publishing events when a user initiates app installation, the app is enabled (after successful installation) or the user uninstalls the app.

* `installed` — the handler creates an entry in the `atlassian_tenants` table
* `enabled` — the handler creates a space in the user's Confluence instance
* `uninstalled` — the handler deletes the entry in `atlassian_tenants`, which is potentially linked to a `slack_team` (also deleted in the process, plus uninstalling from Slack)

Official docs https://developer.atlassian.com/cloud/confluence/connect-app-descriptor

### PR DESCRIPTION
**Pull request by jcpsantiago**
📓 Description

_Summary of the change and link to any relevant tickets. New aliases should include details of why they are valuable_

This PR adds the necessary lifecycle endpoints for Atlassian. After this the app is able to add/remove Atlassian tenants.

It's another large one, because most of the code is coming from the previous codebase.

Resolve #30 

:octocat: Type of change

_Please tick `x` relevant options, delete those not relevant_

- [x] New feature
- [x] Documentation

:beetle: How Has This Been Tested?

- [ ] unit test
- [x] linter check
- [x] GitHub Action checkers

:eyes: Checklist

- [x] Code follows the [Practicalli cljstyle configuration](https://practical.li/clojure/clojure-cli/clojure-style/#cljstyle)
- [ ] Add / update alias docs and README where relevant
- [x] Changelog entry describing notable changes
- [ ] Request maintainers review the PR

### CODE REVIEW

**Comment by jcpsantiago** [comment]
@practicalli-john I'm particularly interested in your opinion regarding safely adding/dropping rows from the db in the `handlers.clj`.
E.g. the `installed` handler will add the credentials to the db, so I guess we should have a `try/catch` here? Then, Atlassian will issue the `enabled` event which hits our handler of the same name, and we create the space in the user's Confluence instance — if any of these steps fail, I think we should "clean up" after ourselves to avoid having credentials we don't need, or the user having spaces they won't use. I'm just not sure what would be the best order/way for doing this safely. Happy to hear your thoughts :)

I don't think you need to go through the other namespaces in depth, but I won't stop you :D 
I'll add some unit tests later on.

**Comment by jcpsantiago** [comment]
> I assume a user is driving actions that may update the database, so that user should be informed what happened in an understandable way.
> 
> So each call to the database should be verified that it worked. If it didn't work, then enough info should be collected so that the user knows what happened and what to do again.
> 
> Either a try catch finally combo or returning a map with details of the error so that the handler can respond with something meaningful
> 
> It is potentially valuable to split out the database code (possibility into another namespace) and ensure failures are handled meaningful ( of course logging errors is useful for the developer, but not the end user)

The user will be interacting with this function in two ways: the "Install" button in the Atlassian marketplace, or the "Upload app" link in the "Manage apps" page of a user's Confluence instance, in case of self-hosting. In either of these scenarios the feedback you get from Atlassian is either "App installed", which is the default even if we respond with 500 to some events, or "Installation failed" without any further info.

In any case, maybe we should keep all the "installation" code in the `installed` handler. Right now the `installed` handler writes to the db, and then the `enabled` handler creates a space for the messages in Confluence. The problem I see is that if the latter fails, the user still sees "Installation successful" 🤷, but if we respond 500 in the former, Confluence shows a (generic) error to the user and it makes it easier to cleanup. At least all the code is close together and easy to see how the cleanup is connected to the mess :D what do you think?

I'll look `with-transaction` 👍

**Comment by practicalli-john** [comment]
Ah, so you are not able to control the content of user interface, that quite a big constraint.  That does seem to negate much of my previous comments.

Ideally I'd strive for at least the correct status, it either worked or did not. But even that seems elusive.

 Are there other ways to show if the install worked?

Or explain in documentation what the status is and how to know if the install worked.

So I'd focus on ensuring connection were closed and queries that could fail were in transactions so they cleaned themselves up (depending the complexity of the query - might not need it for simple queries that fail without affecting the database state)

**Comment by jcpsantiago** [comment]
After the installation completes, even when something goes wrong, the user sees a happy modal with a button to "Get started". This takes them to a page we control - today it has a button to connect slack and some basic instructions, but we are in full control of the content.

I think we could use that page to inform the user of problems, plus via Slack once it's also installed (they are independent things). This means we need to save this state until it's solved 🤔

The simplest thing of all would be to fail install. I'll start with that by moving everything into the installed handler and dropping the enabled handler

**Comment by jcpsantiago** [comment]
* Refactored the db functions into their own namespace
* Added checks to the possible error points
* Added a new call to GET the current spaces in Confluence, only attempt creation if the needed space doesn't exist (e.g. in case someone installed the app, used it, uninstalled and now installed again)

After some more exploration I figured out it's not possible to call the Confluence API before the `enabled` event.

I'm much happier with the structure now.

**Pull request merged**
